#!/bin/bash
i=1
for lines in `cat ./boot/mark`			#non existent in 1st installation
do
  case ${i} in
  1) var1=${lines};;
  esac
  i=`expr ${i} + 1`
done
echo "$var1"							          #0 at first installation

if test "$var1" = "0"; then
  sudo mkdir /etc/X11/xorg.conf.d		
  sudo apt-get install -y xserver-xorg-input-evdev
  sudo cp -f /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf
  sudo apt-get install -y evtest tslib libts-bin
  echo "1" > ./boot/mark
fi

sudo cp ./usr/tft9341-overlay.dtb /boot/overlays/
sudo cp ./usr/tft9341-overlay.dtb /boot/overlays/tft9341.dtbo
echo "Copied tft overlays"
sudo cp -f ./usr/99-calibration.conf-32  /etc/X11/xorg.conf.d/99-calibration.conf
echo "Copied 99-calibration file"
sudo cp -f ./usr/99-fbturbo.conf  /usr/share/X11/xorg.conf.d/
echo "Copied 99-fbturbo file"
if [ -b /dev/mmcblk0p7 ]; then
  sudo cp ./usr/cmdline.txt-noobs /boot/cmdline.txt
else
  sudo cp ./usr/cmdline.txt /boot/
fi 
echo "Copied cmdline.txt"
sudo cp ./usr/inittab /etc/
sudo cp ./boot/config-32.txt /boot/config.txt
echo "Copied config.txt"
arch=$(uname -m)
kernel=$(uname -r)
version=$(uname -v)
if [ $arch = "armv7l" ] || [ $arch = "armv6l" ]; then
  echo "This is an $arch architecture, assuming Raspberry Pi"
#  version=${version%% *}
#  version=${version#*#}
#  echo $version
#  if test $version -lt 970 
#  then
#     echo "rebooting"
#  else
#    echo "need to update touch configuration"
#    if test $version -ge 1023
#    then
#      echo "install xserver-xorg-input-evdev_2.10.5-1"
#      sudo dpkg -i -B xserver-xorg-input-evdev_2.10.5-1_armhf.deb
#    else
#      echo "install xserver-xorg-input-evdev_1%3a2.10.3-1"
#      sudo dpkg -i -B xserver-xorg-input-evdev_1%3a2.10.3-1_armhf.deb
#    fi
#    sudo cp -rf /usr/share/X11/xorg.conf.d/10-evdev.conf /usr/share/X11/xorg.conf.d/45-evdev.conf
#    echo "rebooting"
#  fi
  echo "Please reboot now!"
else
  echo "this is not a raspberrypi kernel, no need to update touch configuration, please reboot now!"
fi
sleep 2
